# Generated by Django 5.2.5 on 2025-09-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='ip_tracking_ip_addr_d89fd9_idx'), models.Index(fields=['path', 'timestamp'], name='ip_tracking_path_148ce7_idx')],
            },
        ),
    ]
